//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    public class Vector4Listener : lisandroct.EventSystem.Listener<UnityEngine.Vector4, Vector4Event, Vector4Response> {
    }
    
    [System.SerializableAttribute()]
    public class Vector4Response : UnityEngine.Events.UnityEvent<UnityEngine.Vector4> {
    }
}
