//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    public class Vector2IntListener : lisandroct.EventSystem.Listener<UnityEngine.Vector2Int, Vector2IntEvent, Vector2IntResponse> {
    }
    
    [System.SerializableAttribute()]
    public class Vector2IntResponse : UnityEngine.Events.UnityEvent<UnityEngine.Vector2Int> {
    }
}
