//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    public class Vector3Listener : lisandroct.EventSystem.Listener<UnityEngine.Vector3, Vector3Event, Vector3Response> {
    }
    
    [System.SerializableAttribute()]
    public class Vector3Response : UnityEngine.Events.UnityEvent<UnityEngine.Vector3> {
    }
}
