//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    public class Vector3IntListener : lisandroct.EventSystem.Listener<UnityEngine.Vector3Int, Vector3IntEvent, Vector3IntResponse> {
    }
    
    [System.SerializableAttribute()]
    public class Vector3IntResponse : UnityEngine.Events.UnityEvent<UnityEngine.Vector3Int> {
    }
}
