//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEditor.CustomEditor(typeof(ElementEvent))]
    public class ElementInspector : lisandroct.EventSystem.EventInspector<RealChem.Element, ElementTest> {
    }
    
    public class ElementTest : lisandroct.EventSystem.TestObject<RealChem.Element> {
    }
}
